In [1]:
# Importing the standard data analysis libraries
import pandas as pd  # pandas 
import numpy as np  # numpy 

# Configuring pandas display options for easier reading in the notebook
pd.set_option('display.max_columns', None)  # show all columns when printing dataframes
pd.set_option('display.max_colwidth', 80)  # allow longer text values to be shown in full
pd.set_option('display.float_format', '{:,.2f}'.format)  # show floats with commas and 2 decimal places

In [3]:
# Loading the raw CSV files 
ct_raw       = pd.read_csv('Corporation_Tax_Data_Tables_2025.csv')  # corporation tax tables
tg_raw       = pd.read_csv('Measuring_tax_gap_online_tables_2025.csv')  # tax gap tables
yield_raw    = pd.read_csv("hmrc_compliance_yield_2024_25.csv", nrows=39)  # compliance yield table; 
# We only keep the first table from this file because the second table is not needed for the analysis
customer_raw = pd.read_csv('hmrc_tax_by_customer_group_2024_25.csv')  # customer group tax data

INSPECTING THE FILES

In [4]:
# Exploring the compliance yield dataset to understand its structure and quality
# Print the number of rows and columns in the dataset
print("SHAPE:", yield_raw.shape)
# Print all column names so we can see the field names
print("\nCOLUMNS:", yield_raw.columns.tolist())
# Print the data type for each column
print("\nDTYPES:\n", yield_raw.dtypes)
# Print how many missing values there are in each column
print("\nNULLS:\n", yield_raw.isnull().sum())
print("\nPREVIEW:\n")
display(yield_raw)  # Show the data so we can visually inspect it

SHAPE: (39, 6)

COLUMNS: ['source', 'publication_year', 'reporting_year', 'directorate', 'tax_regime', 'yield_gbp_million']

DTYPES:
 source                   str
publication_year       int64
reporting_year           str
directorate              str
tax_regime               str
yield_gbp_million    float64
dtype: object

NULLS:
 source               0
publication_year     0
reporting_year       0
directorate          0
tax_regime           0
yield_gbp_million    2
dtype: int64

PREVIEW:

,source,publication_year,reporting_year,directorate,tax_regime,yield_gbp_million
0,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Corporation Tax,"6,149.00"
1,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Excise,698.00
2,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Income Tax,62.00
3,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,VAT,"5,289.00"
4,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Other compliance interventions,"3,629.00"
5,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,TOTAL,"15,827.00"
6,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Corporation Tax,"2,126.00"
7,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Excise,0.00
8,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Income Tax,"2,732.00"
9,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,VAT,"1,788.00"
10,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Other compliance interventions,"2,501.00"
11,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,TOTAL,"9,147.00"
12,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Corporation Tax,596.00
13,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Excise,359.00
14,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Income Tax,"2,060.00"
15,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,VAT,"1,864.00"
16,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Other compliance interventions,"1,453.00"
17,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,TOTAL,"6,333.00"
18,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Corporation Tax,343.00
19,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Excise,"1,769.00"
20,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Income Tax,211.00
21,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,VAT,"1,110.00"
22,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Other compliance interventions,512.00
23,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,TOTAL,"3,946.00"
24,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Corporation Tax,4.00
25,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Excise,"1,055.00"
26,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Income Tax,902.00
27,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,VAT,732.00
28,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Other compliance interventions,348.00
29,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,TOTAL,"3,041.00"
30,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Corporation Tax,80.00
31,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Excise,NaN
32,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Income Tax,236.00
33,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,VAT,NaN
34,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Other compliance interventions,615.00
35,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,TOTAL,931.00
36,HMRC Compliance Yield Technical Note,2025,2024-25,Other customer group activities,Other compliance activities,"8,779.00"
37,HMRC Compliance Yield Technical Note,2025,2024-25,Other customer group activities,TOTAL,"8,779.00"
38,HMRC Compliance Yield Technical Note,2025,2024-25,ALL DIRECTORATES,GRAND TOTAL (discounted),"48,004.00"

In [5]:
# Exploring the customer group dataset to understand what information it contains
# Printing the overall shape of the customer dataset
print("SHAPE:", customer_raw.shape)
display(customer_raw)  # Shows the raw rows so we can inspect the values
# Printing how many missing values each column has
print("\nNULLS:\n", customer_raw.isnull().sum())

SHAPE: (5, 13)

,source,publication_year,reporting_year,customer_group,definition,population,estimated_paye_and_nics_receipts_gbp_bn,estimated_other_tax_receipts_gbp_bn,estimated_compliance_yield_gbp_bn,estimated_compliance_spend_gbp_mn,estimated_tax_gap_gbp_bn,tax_gap_reference_year,notes
0,HMRC Tax by Different Customer Groups,2025,2024-25,Individual customers,Incomes below £200k and assets below £2m in each of last 3 years,37000000,355,20,3.50,540,2.20,2023-24,PAYE receipts counted twice (attributed to both business and individual grou...
1,HMRC Tax by Different Customer Groups,2025,2024-25,Wealthy individuals,Incomes of £200k+ or assets equal to or above £2m in any of last 3 years,950000,70,55,3.70,290,2.10,2023-24,"PAYE receipts counted twice; other taxes includes SA, CGT"
2,HMRC Tax by Different Customer Groups,2025,2024-25,Small businesses,Turnover below £10m and typically fewer than 20 employees; approx 93% of UK ...,5100000,45,100,7.80,750,28.00,2023-24,PAYE tax gap reported here not in individual group
3,HMRC Tax by Different Customer Groups,2025,2024-25,Mid-sized businesses (charities and public bodies),Turnover £10m–£200m or typically 20+ employees; approx 6% of UK businesses,380000,230,70,7.40,350,4.40,2023-24,Population figure is Corporation Tax registered entities
4,HMRC Tax by Different Customer Groups,2025,2024-25,Large businesses,Turnover exceeding £200m; also assessed on complexity risk and global mobility,2000,145,190,19.70,340,5.80,2023-24,Some compliance yield directed at organised crime not included

NULLS:
 source                                     0
publication_year                           0
reporting_year                             0
customer_group                             0
definition                                 0
population                                 0
estimated_paye_and_nics_receipts_gbp_bn    0
estimated_other_tax_receipts_gbp_bn        0
estimated_compliance_yield_gbp_bn          0
estimated_compliance_spend_gbp_mn          0
estimated_tax_gap_gbp_bn                   0
tax_gap_reference_year                     0
notes                                      0
dtype: int64

In [8]:
# Inspecting the corporation tax raw dataset structure
# Prints the number of rows and columns in the file
print("SHAPE:", ct_raw.shape)
# Prints the different SourceSheet values used inside the flattened file
print("\nUNIQUE SOURCE SHEETS:", ct_raw["SourceSheet"].unique())

SHAPE: (651, 26)

UNIQUE SOURCE SHEETS: <StringArray>
[          'Cover',        'Contents',        'Table_1A',        'Table_1B',
     'Tables_2A,B',     'Tables_3A,B', 'Tables_4A,B,C,D',         'Table_5',
         'Table_6',     'Tables_7A,B',         'Table_8',         'Table_9',
    'Tables_10A,B',    'Tables_11A,B',    'Tables_12A,B',    'Tables_13A,B',
    'Tables_14A,B']
Length: 17, dtype: str

In [9]:
# Inspects the tax gap raw dataset structure
# Prints the number of rows and columns in this source file
print("SHAPE:", tg_raw.shape)
# Prints the sheet identifiers available in this file
print("\nUNIQUE SOURCE SHEETS:", tg_raw["SourceSheet"].unique())

SHAPE: (1279, 80)

UNIQUE SOURCE SHEETS: <StringArray>
[       'Cover_note',          'Contents',             'Notes',
         'Table 1.1',         'Table 1.2',         'Table 1.3',
         'Table 1.4',         'Table 1.5',         'Table 1.6',
         'Table 2.1',         'Table 2.2',   'Table 3.1 - 3.2',
   'Table 3.3 - 3.4',   'Table 3.5 - 3.6',  'Table 3.7 - 3.10',
 'Table 3.11 - 3.18', 'Table 3.19 - 3.20', 'Table 3.21 - 3.24',
        'Table 3.25', 'Table 3.26 - 3.36', 'Table 3.37 - 3.47',
 'Table 3.48 - 3.53', 'Table 3.54 - 3.59',         'Table 4.1',
         'Table 4.2',         'Table 4.3',         'Table 4.4',
         'Table 4.5',         'Table 4.6',         'Table 4.7',
         'Table 4.8',         'Table 4.9',        'Table 4.10',
        'Table 4.11',        'Table 4.12',        'Table 4.13',
        'Table 4.14',        'Table 4.15',        'Table 4.16',
        'Table 4.17',        'Table 4.18',         'Table 5.1',
         'Table 5.2',         'Table 5.3',         'Table 5.4',
         'Table 5.5',         'Table 6.1',         'Table 6.2',
         'Table 6.3',         'Table 6.4',         'Table 6.5',
         'Table 6.6',         'Table 6.7',         'Table 7.1',
         'Table 7.2']
Length: 55, dtype: str

CLEANING

In [10]:
# Makes a working copy of the compliance yield table before we clean it
# Copying the data keeps the raw input unchanged if we need to re-run or inspect it later
df_yield = yield_raw.copy()
display(df_yield)  # Show the raw data after copying it

,source,publication_year,reporting_year,directorate,tax_regime,yield_gbp_million
0,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Corporation Tax,"6,149.00"
1,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Excise,698.00
2,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Income Tax,62.00
3,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,VAT,"5,289.00"
4,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,Other compliance interventions,"3,629.00"
5,HMRC Compliance Yield Technical Note,2025,2024-25,Large Business Directorate,TOTAL,"15,827.00"
6,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Corporation Tax,"2,126.00"
7,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Excise,0.00
8,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Income Tax,"2,732.00"
9,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,VAT,"1,788.00"
10,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Other compliance interventions,"2,501.00"
11,HMRC Compliance Yield Technical Note,2025,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,TOTAL,"9,147.00"
12,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Corporation Tax,596.00
13,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Excise,359.00
14,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Income Tax,"2,060.00"
15,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,VAT,"1,864.00"
16,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,Other compliance interventions,"1,453.00"
17,HMRC Compliance Yield Technical Note,2025,2024-25,Individuals and Small Business Compliance Directorate,TOTAL,"6,333.00"
18,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Corporation Tax,343.00
19,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Excise,"1,769.00"
20,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Income Tax,211.00
21,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,VAT,"1,110.00"
22,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,Other compliance interventions,512.00
23,HMRC Compliance Yield Technical Note,2025,2024-25,Fraud Investigation Service,TOTAL,"3,946.00"
24,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Corporation Tax,4.00
25,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Excise,"1,055.00"
26,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Income Tax,902.00
27,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,VAT,732.00
28,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,Other compliance interventions,348.00
29,HMRC Compliance Yield Technical Note,2025,2024-25,Risk and Intelligence Service Directorate,TOTAL,"3,041.00"
30,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Corporation Tax,80.00
31,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Excise,NaN
32,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Income Tax,236.00
33,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,VAT,NaN
34,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,Other compliance interventions,615.00
35,HMRC Compliance Yield Technical Note,2025,2024-25,Counter-Avoidance Directorate,TOTAL,931.00
36,HMRC Compliance Yield Technical Note,2025,2024-25,Other customer group activities,Other compliance activities,"8,779.00"
37,HMRC Compliance Yield Technical Note,2025,2024-25,Other customer group activities,TOTAL,"8,779.00"
38,HMRC Compliance Yield Technical Note,2025,2024-25,ALL DIRECTORATES,GRAND TOTAL (discounted),"48,004.00"

In [ ]:
# Dropping columns that are not needed for this analysis
df_yield = df_yield.drop(columns=['source', 'publication_year'])

 # Renaming columns to shorter and clearer names for future calculations
df_yield = df_yield.rename(columns={
    'reporting_year':     'year',
    'directorate':        'directorate',
    'tax_regime':         'tax_regime',
    'yield_gbp_million':  'yield_gbp_m'
})

# Prints the data types after renaming to verify the table structure
print(df_yield.dtypes)
display(df_yield)

year               str
directorate        str
tax_regime         str
yield_gbp_m    float64
dtype: object

,year,directorate,tax_regime,yield_gbp_m
0,2024-25,Large Business Directorate,Corporation Tax,"6,149.00"
1,2024-25,Large Business Directorate,Excise,698.00
2,2024-25,Large Business Directorate,Income Tax,62.00
3,2024-25,Large Business Directorate,VAT,"5,289.00"
4,2024-25,Large Business Directorate,Other compliance interventions,"3,629.00"
5,2024-25,Large Business Directorate,TOTAL,"15,827.00"
6,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Corporation Tax,"2,126.00"
7,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Excise,0.00
8,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Income Tax,"2,732.00"
9,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,VAT,"1,788.00"
10,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Other compliance interventions,"2,501.00"
11,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,TOTAL,"9,147.00"
12,2024-25,Individuals and Small Business Compliance Directorate,Corporation Tax,596.00
13,2024-25,Individuals and Small Business Compliance Directorate,Excise,359.00
14,2024-25,Individuals and Small Business Compliance Directorate,Income Tax,"2,060.00"
15,2024-25,Individuals and Small Business Compliance Directorate,VAT,"1,864.00"
16,2024-25,Individuals and Small Business Compliance Directorate,Other compliance interventions,"1,453.00"
17,2024-25,Individuals and Small Business Compliance Directorate,TOTAL,"6,333.00"
18,2024-25,Fraud Investigation Service,Corporation Tax,343.00
19,2024-25,Fraud Investigation Service,Excise,"1,769.00"
20,2024-25,Fraud Investigation Service,Income Tax,211.00
21,2024-25,Fraud Investigation Service,VAT,"1,110.00"
22,2024-25,Fraud Investigation Service,Other compliance interventions,512.00
23,2024-25,Fraud Investigation Service,TOTAL,"3,946.00"
24,2024-25,Risk and Intelligence Service Directorate,Corporation Tax,4.00
25,2024-25,Risk and Intelligence Service Directorate,Excise,"1,055.00"
26,2024-25,Risk and Intelligence Service Directorate,Income Tax,902.00
27,2024-25,Risk and Intelligence Service Directorate,VAT,732.00
28,2024-25,Risk and Intelligence Service Directorate,Other compliance interventions,348.00
29,2024-25,Risk and Intelligence Service Directorate,TOTAL,"3,041.00"
30,2024-25,Counter-Avoidance Directorate,Corporation Tax,80.00
31,2024-25,Counter-Avoidance Directorate,Excise,NaN
32,2024-25,Counter-Avoidance Directorate,Income Tax,236.00
33,2024-25,Counter-Avoidance Directorate,VAT,NaN
34,2024-25,Counter-Avoidance Directorate,Other compliance interventions,615.00
35,2024-25,Counter-Avoidance Directorate,TOTAL,931.00
36,2024-25,Other customer group activities,Other compliance activities,"8,779.00"
37,2024-25,Other customer group activities,TOTAL,"8,779.00"
38,2024-25,ALL DIRECTORATES,GRAND TOTAL (discounted),"48,004.00"

In [ ]:
# Converting the yield column to numeric values so we can perform calculations
df_yield['yield_gbp_m'] = pd.to_numeric(df_yield['yield_gbp_m'], errors='coerce')
# Prints the number of values that could not be converted to a number
print("Nulls after coerce:", df_yield['yield_gbp_m'].isnull().sum())
display(df_yield)  # Shows the cleaned yield dataset

Nulls after coerce: 2

,year,directorate,tax_regime,yield_gbp_m
0,2024-25,Large Business Directorate,Corporation Tax,"6,149.00"
1,2024-25,Large Business Directorate,Excise,698.00
2,2024-25,Large Business Directorate,Income Tax,62.00
3,2024-25,Large Business Directorate,VAT,"5,289.00"
4,2024-25,Large Business Directorate,Other compliance interventions,"3,629.00"
5,2024-25,Large Business Directorate,TOTAL,"15,827.00"
6,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Corporation Tax,"2,126.00"
7,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Excise,0.00
8,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Income Tax,"2,732.00"
9,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,VAT,"1,788.00"
10,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,Other compliance interventions,"2,501.00"
11,2024-25,Wealthy and Mid-Sized Business Compliance Directorate,TOTAL,"9,147.00"
12,2024-25,Individuals and Small Business Compliance Directorate,Corporation Tax,596.00
13,2024-25,Individuals and Small Business Compliance Directorate,Excise,359.00
14,2024-25,Individuals and Small Business Compliance Directorate,Income Tax,"2,060.00"
15,2024-25,Individuals and Small Business Compliance Directorate,VAT,"1,864.00"
16,2024-25,Individuals and Small Business Compliance Directorate,Other compliance interventions,"1,453.00"
17,2024-25,Individuals and Small Business Compliance Directorate,TOTAL,"6,333.00"
18,2024-25,Fraud Investigation Service,Corporation Tax,343.00
19,2024-25,Fraud Investigation Service,Excise,"1,769.00"
20,2024-25,Fraud Investigation Service,Income Tax,211.00
21,2024-25,Fraud Investigation Service,VAT,"1,110.00"
22,2024-25,Fraud Investigation Service,Other compliance interventions,512.00
23,2024-25,Fraud Investigation Service,TOTAL,"3,946.00"
24,2024-25,Risk and Intelligence Service Directorate,Corporation Tax,4.00
25,2024-25,Risk and Intelligence Service Directorate,Excise,"1,055.00"
26,2024-25,Risk and Intelligence Service Directorate,Income Tax,902.00
27,2024-25,Risk and Intelligence Service Directorate,VAT,732.00
28,2024-25,Risk and Intelligence Service Directorate,Other compliance interventions,348.00
29,2024-25,Risk and Intelligence Service Directorate,TOTAL,"3,041.00"
30,2024-25,Counter-Avoidance Directorate,Corporation Tax,80.00
31,2024-25,Counter-Avoidance Directorate,Excise,NaN
32,2024-25,Counter-Avoidance Directorate,Income Tax,236.00
33,2024-25,Counter-Avoidance Directorate,VAT,NaN
34,2024-25,Counter-Avoidance Directorate,Other compliance interventions,615.00
35,2024-25,Counter-Avoidance Directorate,TOTAL,931.00
36,2024-25,Other customer group activities,Other compliance activities,"8,779.00"
37,2024-25,Other customer group activities,TOTAL,"8,779.00"
38,2024-25,ALL DIRECTORATES,GRAND TOTAL (discounted),"48,004.00"

In [14]:
# Computes the total compliance yield across all reported directorates
print("Total compliance yield 2024-25: £{:,.0f}m".format(df_yield['yield_gbp_m'].sum()))
# The dataset stores values in millions of pounds, so the sum is expressed in £m

Total compliance yield 2024-25: £144,010m

In [15]:
# Copying the customer dataset so we can clean it without changing the original source data
df_cust = customer_raw.copy()
# Transposing the DataFrame when displaying so each row is easier to inspect visually
display(df_cust.T)   # Transposed view for readability

,0,1,2,3,4
source,HMRC Tax by Different Customer Groups,HMRC Tax by Different Customer Groups,HMRC Tax by Different Customer Groups,HMRC Tax by Different Customer Groups,HMRC Tax by Different Customer Groups
publication_year,2025,2025,2025,2025,2025
reporting_year,2024-25,2024-25,2024-25,2024-25,2024-25
customer_group,Individual customers,Wealthy individuals,Small businesses,Mid-sized businesses (charities and public bodies),Large businesses
definition,Incomes below £200k and assets below £2m in each of last 3 years,Incomes of £200k+ or assets equal to or above £2m in any of last 3 years,Turnover below £10m and typically fewer than 20 employees; approx 93% of UK ...,Turnover £10m–£200m or typically 20+ employees; approx 6% of UK businesses,Turnover exceeding £200m; also assessed on complexity risk and global mobility
population,37000000,950000,5100000,380000,2000
estimated_paye_and_nics_receipts_gbp_bn,355,70,45,230,145
estimated_other_tax_receipts_gbp_bn,20,55,100,70,190
estimated_compliance_yield_gbp_bn,3.50,3.70,7.80,7.40,19.70
estimated_compliance_spend_gbp_mn,540,290,750,350,340
estimated_tax_gap_gbp_bn,2.20,2.10,28.00,4.40,5.80
tax_gap_reference_year,2023-24,2023-24,2023-24,2023-24,2023-24
notes,PAYE receipts counted twice (attributed to both business and individual grou...,"PAYE receipts counted twice; other taxes includes SA, CGT",PAYE tax gap reported here not in individual group,Population figure is Corporation Tax registered entities,Some compliance yield directed at organised crime not included

In [16]:
# Removing columns that are not useful for the analysis
df_cust = df_cust.drop(columns=['source', 'publication_year', 'tax_gap_reference_year', 'notes'])

# Renaming columns to shorter, more descriptive names
df_cust = df_cust.rename(columns={
    'reporting_year':                           'year',
    'customer_group':                           'segment',
    'definition':                               'segment_definition',
    'population':                               'population',
    'estimated_paye_and_nics_receipts_gbp_bn':  'paye_nics_receipts_gbp_bn',
    'estimated_other_tax_receipts_gbp_bn':      'other_receipts_gbp_bn',
    'estimated_compliance_yield_gbp_bn':        'compliance_yield_gbp_bn',
    'estimated_compliance_spend_gbp_mn':        'compliance_spend_gbp_m',
    'estimated_tax_gap_gbp_bn':                 'tax_gap_gbp_bn',
})

In [17]:
# Converting the numeric-looking columns to actual numeric data types
# This allows us to use math and summary statistics on these columns
numeric_cols = [
    'population', 'paye_nics_receipts_gbp_bn', 'other_receipts_gbp_bn',
    'compliance_yield_gbp_bn', 'compliance_spend_gbp_m', 'tax_gap_gbp_bn'
]
for col in numeric_cols:
    df_cust[col] = pd.to_numeric(df_cust[col], errors='coerce')  # invalid values become NaN
display(df_cust)  # Verifying the cleaned customer table

,year,segment,segment_definition,population,paye_nics_receipts_gbp_bn,other_receipts_gbp_bn,compliance_yield_gbp_bn,compliance_spend_gbp_m,tax_gap_gbp_bn
0,2024-25,Individual customers,Incomes below £200k and assets below £2m in each of last 3 years,37000000,355,20,3.50,540,2.20
1,2024-25,Wealthy individuals,Incomes of £200k+ or assets equal to or above £2m in any of last 3 years,950000,70,55,3.70,290,2.10
2,2024-25,Small businesses,Turnover below £10m and typically fewer than 20 employees; approx 93% of UK ...,5100000,45,100,7.80,750,28.00
3,2024-25,Mid-sized businesses (charities and public bodies),Turnover £10m–£200m or typically 20+ employees; approx 6% of UK businesses,380000,230,70,7.40,350,4.40
4,2024-25,Large businesses,Turnover exceeding £200m; also assessed on complexity risk and global mobility,2000,145,190,19.70,340,5.80

In [ ]:
# Calculates useful customer segment metrics from the cleaned data
# 1) Compliance yield as a percentage of the tax gap
df_cust['yield_pct_of_gap'] = (
    df_cust['compliance_yield_gbp_bn'] / df_cust['tax_gap_gbp_bn'] * 100
).round(1)
# 2) Cost of compliance per £1 of yield
df_cust['spend_per_pound_yield'] = (
    (df_cust['compliance_spend_gbp_m'] / 1000) / df_cust['compliance_yield_gbp_bn']
).round(3)
# 3) Average tax gap per person or entity in the segment
df_cust['tax_gap_per_entity_gbp'] = (
    (df_cust['tax_gap_gbp_bn'] * 1e9) / df_cust['population']
).round(0)
display(df_cust[['segment', 'tax_gap_gbp_bn', 'compliance_yield_gbp_bn',
                  'yield_pct_of_gap', 'spend_per_pound_yield', 'tax_gap_per_entity_gbp']])

,segment,tax_gap_gbp_bn,compliance_yield_gbp_bn,yield_pct_of_gap,spend_per_pound_yield,tax_gap_per_entity_gbp
0,Individual customers,2.20,3.50,159.10,0.15,59.00
1,Wealthy individuals,2.10,3.70,176.20,0.08,"2,211.00"
2,Small businesses,28.00,7.80,27.90,0.10,"5,490.00"
3,Mid-sized businesses (charities and public bodies),4.40,7.40,168.20,0.05,"11,579.00"
4,Large businesses,5.80,19.70,339.70,0.02,"2,900,000.00"

EXTRACT TABLE 6 — Sector snapshot

In [19]:
# Extract only the rows that belong to Table 6 within the corporation tax file
t6_raw = ct_raw[ct_raw['SourceSheet'] == 'Table_6'].copy()
# Identify which columns actually contain data for Table 6
non_null = [col for col in ct_raw.columns if t6_raw[col].notna().any()]
print("Non-null columns in Table_6:")
for c in non_null:
    print(" ", c)

Non-null columns in Table_6:
  SourceSheet
  Unnamed: 1
  Unnamed: 2
  Unnamed: 3
  Unnamed: 4
  Unnamed: 5
  Unnamed: 6
  Profits, losses and tax liability by Standard Industrial Classification (SIC) section, financial year 2023-24
  Unnamed: 7
  Unnamed: 8

 Identify the header row and data rows

In [20]:
# Locate the row that contains the header labels for Table 6
# We search for the word 'Industry' which appears in the header row
header_mask = t6_raw.apply(lambda row: row.astype(str).str.contains('Industry').any(), axis=1)
print("Header row index:", t6_raw[header_mask].index.tolist())
display(t6_raw[header_mask])  # Show the header row identified by the mask

Header row index: [260]

,SourceSheet,Annual UK Corporation Tax Statistics 2025,Contents,Unnamed: 1,"Corporate Tax receipts by type, 2019-20 to 2024-25",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,"Corporation Tax receipts by Standard Industrial Classification (SIC) section, 2019-20 to 2024-25","Corporate Tax liabilities by type, 2018-19 to 2023-24","Profits, losses, deductions and tax liabilities, 2018-19 to 2023-24","Profits, losses, deductions and tax liabilities by broad company sector, 2018-19 to 2023-24","Corporation Tax chargeable by Standard Industrial Classification (SIC) section, financial year 2023-24","Profits, losses and tax liability by Standard Industrial Classification (SIC) section, financial year 2023-24",Unnamed: 7,Unnamed: 8,"Tax liability by Standard Industrial Classification (SIC) section, 2018-19 to 2023-24","Tax liability by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24","Number of companies liable to pay tax by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24","Tax liability by band, 2018-19 to 2023-24","Tax liability by estimated company size, 2018-19 to 2023-24","Summary of capital allowances by year, 2018-19 to 2023-24","Capital allowances by band, 2018-19 to 2023-24","Summary of capital allowances qualifying expenditure by year, 2018-19 to 2023-24"
260,Table_6,NaN,NaN,Companies submitting a CT Return,NaN,Companies with > £0 tax payable,Total profits and other taxable income,Trading losses arising in-year,Capital allowances included in profits and losses,In-year and brought forward losses claimed against profits,NaN,NaN,NaN,NaN,NaN,Industry,Group relief including carried forward group relief,Corporation Tax payable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Building the clean Table 6 dataframe

In [21]:
# Build the cleaned Table 6 DataFrame from the raw data
# Keep only columns that have values for the Table 6 rows
t6 = t6_raw[non_null].copy()

# Define the sector description column from the sheet
sector_col = 'Profits, losses and tax liability by Standard Industrial Classification (SIC) section, financial year 2023-24'

# Filter to rows where the sector column starts with a sector code like 'A.' or 'B.'
sector_mask = t6[sector_col].astype(str).str.match(r'^[A-U]\\.')
t6_sectors = t6[sector_mask].copy()

# Rename the generic 'Unnamed' columns to meaningful names
t6_sectors = t6_sectors.rename(columns={
    'Unnamed: 1':  'companies_filing_ct_return',
    'Unnamed: 2':  'companies_with_tax_payable',
    'Unnamed: 3':  'total_profits_gbp_m',
    'Unnamed: 4':  'trading_losses_gbp_m',
    'Unnamed: 5':  'capital_allowances_gbp_m',
    'Unnamed: 6':  'losses_claimed_gbp_m',
    sector_col:    'sector',
    'Unnamed: 7':  'group_relief_gbp_m',
    'Unnamed: 8':  'ct_payable_gbp_m'
})

# Drop the SourceSheet column since all rows are now from Table 6
t6_sectors = t6_sectors.drop(columns=['SourceSheet'])

# Convert the columns that should contain numbers into numeric type
num_cols_t6 = [
    'companies_filing_ct_return', 'companies_with_tax_payable',
    'total_profits_gbp_m', 'trading_losses_gbp_m',
    'capital_allowances_gbp_m', 'losses_claimed_gbp_m',
    'group_relief_gbp_m', 'ct_payable_gbp_m'
 ]
for col in num_cols_t6:
    t6_sectors[col] = pd.to_numeric(t6_sectors[col], errors='coerce')

# Extract a short sector code and the clean sector name
t6_sectors['sector_code'] = t6_sectors['sector'].str.extract(r'^([A-U])\\.')
t6_sectors['sector_name'] = t6_sectors['sector'].str.replace(r'^[A-U]\\.\\s*', '', regex=True)

# Reset the index after filtering rows
t6_sectors = t6_sectors.reset_index(drop=True)
display(t6_sectors[['sector_code', 'sector_name', 'companies_with_tax_payable',
                     'total_profits_gbp_m', 'ct_payable_gbp_m']])

Empty DataFrame
Columns: [sector_code, sector_name, companies_with_tax_payable, total_profits_gbp_m, ct_payable_gbp_m]
Index: []

Derive sector-level ratios

In [22]:
# Deriving useful ratios for the sector snapshot table
# Calculating corporate tax payable per company in thousands of pounds
t6_sectors['ct_per_company_gbp_k'] = (
    (t6_sectors['ct_payable_gbp_m'] * 1000) / t6_sectors['companies_with_tax_payable']
).round(1)

# Calculating the effective tax rate: tax paid relative to profits
t6_sectors['effective_ct_rate_pct'] = (
    t6_sectors['ct_payable_gbp_m'] / t6_sectors['total_profits_gbp_m'] * 100
).round(2)

# Calculating the loss ratio: trading losses as a percentage of profits
t6_sectors['loss_ratio_pct'] = (
    t6_sectors['trading_losses_gbp_m'] / t6_sectors['total_profits_gbp_m'] * 100
).round(2)

display(t6_sectors[['sector_code', 'sector_name', 'ct_payable_gbp_m',
                     'ct_per_company_gbp_k', 'effective_ct_rate_pct', 'loss_ratio_pct']])

Empty DataFrame
Columns: [sector_code, sector_name, ct_payable_gbp_m, ct_per_company_gbp_k, effective_ct_rate_pct, loss_ratio_pct]
Index: []

Tax liability time series (by SIC division)

In [ ]:
# Extracting the raw Table 8 rows from the corporation tax dataset
t8_raw = ct_raw[ct_raw['SourceSheet'] == 'Table_8'].copy()
non_null_8 = [col for col in ct_raw.columns if t8_raw[col].notna().any()]

# Inspecting the header row by searching for the label that identifies the SIC code column
header_mask_8 = t8_raw['Unnamed: 1'].astype(str).str.contains('SIC 2007 Code')
print("Header row(s):")
display(t8_raw[header_mask_8])

Header row(s):

,SourceSheet,Annual UK Corporation Tax Statistics 2025,Contents,Unnamed: 1,"Corporate Tax receipts by type, 2019-20 to 2024-25",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,"Corporation Tax receipts by Standard Industrial Classification (SIC) section, 2019-20 to 2024-25","Corporate Tax liabilities by type, 2018-19 to 2023-24","Profits, losses, deductions and tax liabilities, 2018-19 to 2023-24","Profits, losses, deductions and tax liabilities by broad company sector, 2018-19 to 2023-24","Corporation Tax chargeable by Standard Industrial Classification (SIC) section, financial year 2023-24","Profits, losses and tax liability by Standard Industrial Classification (SIC) section, financial year 2023-24",Unnamed: 7,Unnamed: 8,"Tax liability by Standard Industrial Classification (SIC) section, 2018-19 to 2023-24","Tax liability by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24","Number of companies liable to pay tax by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24","Tax liability by band, 2018-19 to 2023-24","Tax liability by estimated company size, 2018-19 to 2023-24","Summary of capital allowances by year, 2018-19 to 2023-24","Capital allowances by band, 2018-19 to 2023-24","Summary of capital allowances qualifying expenditure by year, 2018-19 to 2023-24"
338,Table_8,NaN,NaN,SIC 2007 Code,NaN,SIC Division,2018-19,2019-20,2020-21,2021-22,NaN,NaN,NaN,NaN,NaN,NaN,2022-23,2023-24,NaN,SIC Section,NaN,NaN,NaN,NaN,NaN,NaN

Building the time series dataframe

In [24]:
# Builds a clean time series table from the raw Table 8 rows
# Keeps only rows whose first column looks like a SIC division code
data_mask_8 = t8_raw['Unnamed: 1'].astype(str).str.match(r'^\d')
t8_data = t8_raw[data_mask_8][non_null_8].copy()

# The human-readable column name for the sector description
year_series_col = 'Tax liability by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24'

# Renames the generic columns to meaningful names
t8_data = t8_data.rename(columns={
    'Unnamed: 1':      'sic_division_code',
    'Unnamed: 2':      'sic_division_name',
    'Unnamed: 3':      'liability_2018_19',
    'Unnamed: 4':      'liability_2019_20',
    'Unnamed: 5':      'liability_2020_21',
    'Unnamed: 6':      'liability_2021_22',
    'Unnamed: 7':      'liability_2022_23',
    'Unnamed: 8':      'liability_2023_24',
    year_series_col:   'sector_section'
})

# Removes the sheet identifier column since this subset is already only Table 8 rows
t8_data = t8_data.drop(columns=['SourceSheet'])

# Converts the liability columns to numeric values and treat confidential markers as missing data
year_cols = ['liability_2018_19', 'liability_2019_20', 'liability_2020_21',
             'liability_2021_22', 'liability_2022_23', 'liability_2023_24']
for col in year_cols:
    t8_data[col] = t8_data[col].replace({'[X]': np.nan, '[x]': np.nan})
    t8_data[col] = pd.to_numeric(t8_data[col], errors='coerce')

# Extracts the broader section code from the sector description
t8_data['sector_code'] = t8_data['sector_section'].str.extract(r'^([A-U])\.')

# Resets the index after filtering and cleaning
t8_data = t8_data.reset_index(drop=True)
print("Shape:", t8_data.shape)
display(t8_data.head(10))

Shape: (85, 10)

,sic_division_code,sic_division_name,liability_2018_19,liability_2019_20,liability_2020_21,liability_2021_22,liability_2022_23,liability_2023_24,sector_section,sector_code
0,1,"Crop and animal production, hunting and related service activities",271,256.00,284,307,406.00,446,"A. Agriculture, Forestry and Fishing",A
1,2,Forestry and logging,20,21.00,26,36,37.00,38,"A. Agriculture, Forestry and Fishing",A
2,3,Fishing and aquaculture,84,78.00,70,68,69.00,74,"A. Agriculture, Forestry and Fishing",A
3,5; 6; 7,Mining of coal and lignite; Extraction of crude petroleum and natural gas; M...,1993,"1,297.00",611,2054,"6,374.00",2765,B. Mining and Quarrying,B
4,8,Other mining and quarrying,73,52.00,48,64,82.00,106,B. Mining and Quarrying,B
5,9,Mining support service activities,107,216.00,306,282,NaN,207,B. Mining and Quarrying,B
6,10,Manufacture of food products,459,428.00,488,446,439.00,616,C. Manufacturing,C
7,11,Manufacture of beverages,375,329.00,260,314,377.00,378,C. Manufacturing,C
8,12; 32,Manufacture of tobacco products; Other manufacturing,552,NaN,617,783,876.00,1008,C. Manufacturing,C
9,13,Manufacture of textiles,106,69.00,112,197,184.00,178,C. Manufacturing,C

Aggregate from SIC division up to SIC section (to match Table 6)

In [25]:
# Aggregates the SIC division liabilities up to the broader SIC section level
t8_section = (
    t8_data
    .groupby('sector_code')[year_cols]
    .sum(min_count=1)   # min_count=1 preserves NaN when all values are missing
    .reset_index()
)

# Calculates the percentage change in liability from 2018-19 to 2023-24
t8_section['liability_change_pct'] = (
    (t8_section['liability_2023_24'] - t8_section['liability_2018_19'])
    / t8_section['liability_2018_19'] * 100
).round(1)

print("Section-level time series:")
display(t8_section)

Section-level time series:

,sector_code,liability_2018_19,liability_2019_20,liability_2020_21,liability_2021_22,liability_2022_23,liability_2023_24,liability_change_pct
0,A,375,355.00,380,411,512.00,558,48.80
1,B,2173,"1,565.00",965,2400,"6,456.00",3078,41.60
2,C,4838,"3,940.00",4434,5245,"5,725.00",6857,41.70
3,D,975,"1,082.00",1220,1481,"3,307.00",5183,431.60
4,E,300,294.00,273,266,275.00,284,-5.30
5,F,4301,"4,333.00",3667,4775,"5,187.00",5575,29.60
6,G,5466,"5,353.00",5797,7631,"7,861.00",8415,54.00
7,H,1231,828.00,857,1086,"1,280.00",1408,14.40
8,I,970,808.00,594,1126,"1,094.00",1180,21.60
9,J,4824,"4,867.00",4718,5214,"5,231.00",5983,24.00
10,K,9831,"11,571.00",11244,13114,"14,890.00",19581,99.20
11,L,2060,"2,005.00",2097,2718,"3,123.00",2706,31.40
12,M,5920,"5,649.00",5322,5878,"6,708.00",7622,28.70
13,N,4460,"4,588.00",4220,5177,"5,994.00",6773,51.90
14,O,106,119.00,100,106,141.00,302,184.90
15,P,237,240.00,251,381,428.00,425,79.30
16,Q,1144,"1,180.00",1479,1709,"1,689.00",2029,77.40
17,R,727,663.00,528,778,990.00,1158,59.30
18,S,929,933.00,918,1020,"1,253.00",1521,63.70
19,T,26,28.00,31,42,39.00,41,57.70
20,U,1286,"1,386.00",1869,2207,"2,238.00",2476,92.50

Company count time series

In [ ]:
# Extracting the company count time series from Table 9
# Keep only rows from the raw file that belong to Table 9
t9_raw = ct_raw[ct_raw['SourceSheet'] == 'Table_9'].copy()
non_null_9 = [col for col in ct_raw.columns if t9_raw[col].notna().any()]

# Data rows start with a SIC division code
data_mask_9 = t9_raw['Unnamed: 1'].astype(str).str.match(r'^\d')
t9_data = t9_raw[data_mask_9][non_null_9].copy()

company_count_col = 'Number of companies liable to pay tax by Standard Industrial Classification (SIC) division, 2018-19 to 2023-24'

# Rename the raw columns to readable names
t9_data = t9_data.rename(columns={
    'Unnamed: 1':        'sic_division_code',
    'Unnamed: 2':        'sic_division_name',
    'Unnamed: 3':        'companies_2018_19',
    'Unnamed: 4':        'companies_2019_20',
    'Unnamed: 5':        'companies_2020_21',
    'Unnamed: 6':        'companies_2021_22',
    'Unnamed: 7':        'companies_2022_23',
    'Unnamed: 8':        'companies_2023_24',
    company_count_col:   'sector_section'
})

# Drops the sheet identifier since we already have the relevant subset
t9_data = t9_data.drop(columns=['SourceSheet'])

# Converts the company count columns to numeric values
company_year_cols = ['companies_2018_19', 'companies_2019_20', 'companies_2020_21',
                     'companies_2021_22', 'companies_2022_23', 'companies_2023_24']
for col in company_year_cols:
    t9_data[col] = t9_data[col].replace({'[X]': np.nan, '[x]': np.nan})
    t9_data[col] = pd.to_numeric(t9_data[col], errors='coerce')

# Extracts the section code from the sector section text
t9_data['sector_code'] = t9_data['sector_section'].str.extract(r'^([A-U])\.')

# Aggregates division counts to the sector section level
t9_section = (
    t9_data
    .groupby('sector_code')[company_year_cols]
    .sum(min_count=1)
    .reset_index()
)

# Calculates percentage change in the number of companies from 2018-19 to 2023-24
t9_section['company_count_change_pct'] = (
    (t9_section['companies_2023_24'] - t9_section['companies_2018_19'])
    / t9_section['companies_2018_19'] * 100
).round(1)

display(t9_section)

,sector_code,companies_2018_19,companies_2019_20,companies_2020_21,companies_2021_22,companies_2022_23,companies_2023_24,company_count_change_pct
0,A,13405,"13,530.00",13860,14310,"14,665.00",14930,11.40
1,B,3725,"3,810.00",3285,2835,"1,005.00",2605,-30.10
2,C,73475,"63,855.00",73335,74000,"73,590.00",75105,2.20
3,D,3565,"3,790.00",3810,3970,"4,395.00",4610,29.30
4,E,4715,"4,705.00",4840,5045,"5,025.00",5120,8.60
5,F,198370,"207,160.00",205925,209710,"214,495.00",218460,10.10
6,G,141125,"150,390.00",165070,173710,"170,850.00",172000,21.90
7,H,52585,"58,820.00",55000,52865,"51,040.00",46365,-11.80
8,I,47090,"50,540.00",57375,62465,"58,160.00",57530,22.20
9,J,175840,"180,315.00",166850,145960,"137,820.00",137650,-21.70
10,K,41730,"43,105.00",42770,43375,"43,650.00",44825,7.40
11,L,96075,"104,670.00",115315,128495,"139,605.00",146210,52.20
12,M,277860,"287,010.00",274250,258625,"250,165.00",255025,-8.20
13,N,161030,"157,565.00",146520,143955,"146,065.00",137785,-14.40
14,O,1880,"2,245.00",2380,2505,"2,740.00",3175,68.90
15,P,21605,"22,800.00",23195,24665,"26,145.00",27705,28.20
16,Q,71370,"77,050.00",80000,82525,"89,070.00",96945,35.80
17,R,29400,"30,370.00",29455,31995,"33,700.00",34950,18.90
18,S,68565,"72,990.00",72525,72720,"71,705.00",73870,7.70
19,T,4750,"5,300.00",5640,5835,"6,110.00",6720,41.50
20,U,15880,"16,520.00",20295,24765,"24,370.00",21530,35.60

Extract CT gap time series

In [27]:
# Extracts the CT gap table from the tax gap dataset
t51_raw = tg_raw[tg_raw['SourceSheet'] == 'Table 5.1'].copy()
non_null_51 = [col for col in tg_raw.columns if t51_raw[col].notna().any()]

# Inspects the header row to confirm the layout of the table
header_51 = t51_raw[non_null_51].iloc[3]  # row 3 appears to be the header row
print("Header row values:")
print(header_51.values)

Header row values:
<StringArray>
['Table 5.1',   '2005-06',   '2006-07',   '2007-08',   '2008-09',   '2009-10',
   '2010-11',   '2011-12',   '2012-13',   '2013-14',   '2014-15',   '2015-16',
   '2016-17',   '2017-18',   '2018-19',   '2019-20',   '2020-21',   '2021-22',
   '2022-23',   '2023-24', 'Component']
Length: 21, dtype: str

Parse the CT gap table into long format

In [ ]:
# Parsing the CT gap table into a clean DataFrame
# Keep only rows that contain actual component names and exclude the header row
t51 = t51_raw[non_null_51].copy()
component_col = 'Table 5.1: Corporation Tax gap (£ billion)'
data_51 = t51[t51[component_col].notna() & (t51[component_col] != 'Component')].copy()

# Lists the year labels for the table columns
year_labels = [
    '2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12',
    '2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19',
    '2019-20','2020-21','2021-22','2022-23','2023-24'
 ]
year_cols_51 = [f'Unnamed: {i}' for i in range(1, 20)]

# Selects only the relevant columns and rename them for clarity
data_51 = data_51[['SourceSheet', component_col] + year_cols_51].copy()
data_51.columns = ['SourceSheet', 'component'] + year_labels

# Converts year values to numeric and remove any percent symbols
for yr in year_labels:
    data_51[yr] = data_51[yr].astype(str).str.replace('%', '', regex=False)
    data_51[yr] = pd.to_numeric(data_51[yr], errors='coerce')

# Removes the helper SourceSheet column before analysis
data_51 = data_51.drop(columns=['SourceSheet']).reset_index(drop=True)
print("CT gap components found:")
print(data_51['component'].tolist())
display(data_51)

CT gap components found:
['This worksheet contains 1 table.', 'This table contains detailed notes: [note 12][note 40][note 49]', 'Estimates are rounded to the nearest £0.1 billion\xa0or\xa0the nearest 0.1%.', 'Gross tax gap', 'Compliance yield', 'Non-payment', 'Net tax gap', 'Liabilities', 'Total theoretical tax liabilities', 'Proportion of liabilities %']

,component,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24
0,This worksheet contains 1 table.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This table contains detailed notes: [note 12][note 40][note 49],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Estimates are rounded to the nearest £0.1 billion or the nearest 0.1%.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gross tax gap,8.80,8.90,7.80,6.90,6.80,6.00,4.80,5.90,6.20,5.60,6.20,6.50,6.60,7.20,10.30,11.30,15.00,16.80,20.30
4,Compliance yield,3.50,4.30,3.50,3.00,3.50,2.70,2.20,3.00,3.00,1.40,1.90,1.70,1.50,1.40,1.40,1.30,1.40,1.80,2.30
5,Non-payment,0.20,0.20,0.40,0.60,0.70,0.60,0.50,0.60,0.40,0.60,0.30,0.40,0.30,0.50,0.60,0.60,0.50,0.60,0.50
6,Net tax gap,5.50,4.90,4.70,4.40,4.10,4.00,3.00,3.60,3.70,4.70,4.60,5.20,5.40,6.30,9.40,10.50,14.20,15.50,18.60
7,Liabilities,43.00,42.80,45.20,42.30,38.40,43.60,44.60,41.50,41.70,45.30,46.60,53.50,56.70,56.10,56.10,53.90,66.50,81.60,98.80
8,Total theoretical tax liabilities,48.50,47.60,50.00,46.70,42.40,47.60,47.60,45.10,45.40,50.00,51.20,58.60,62.10,62.30,65.50,64.50,80.70,97.10,117.40
9,Proportion of liabilities %,11.40,10.20,9.50,9.40,9.60,8.30,6.40,7.90,8.10,9.50,9.00,8.80,8.80,10.10,14.30,16.40,17.60,16.00,15.80

Pivot to long format for dashboard use

In [ ]:
# Pivots the CT gap table from wide format to long format
ct_gap_long = data_51.melt(
    id_vars='component',
    var_name='year',
    value_name='value_gbp_bn'
 )

# Keeps only the main CT components we need for analysis
keep_components = ['Gross tax gap', 'Net tax gap', 'Compliance yield',
                   'Liabilities', 'Proportion of liabilities %']
ct_gap_long = ct_gap_long[ct_gap_long['component'].isin(keep_components)]

print("Shape:", ct_gap_long.shape)
display(ct_gap_long.head(20))

Shape: (95, 3)

                      component     year  value_gbp_bn
3                 Gross tax gap  2005-06          8.80
4              Compliance yield  2005-06          3.50
6                   Net tax gap  2005-06          5.50
7                   Liabilities  2005-06         43.00
9   Proportion of liabilities %  2005-06         11.40
13                Gross tax gap  2006-07          8.90
14             Compliance yield  2006-07          4.30
16                  Net tax gap  2006-07          4.90
17                  Liabilities  2006-07         42.80
19  Proportion of liabilities %  2006-07         10.20
23                Gross tax gap  2007-08          7.80
24             Compliance yield  2007-08          3.50
26                  Net tax gap  2007-08          4.70
27                  Liabilities  2007-08         45.20
29  Proportion of liabilities %  2007-08          9.50
33                Gross tax gap  2008-09          6.90
34             Compliance yield  2008-09          3.00
36                  Net tax gap  2008-09          4.40
37                  Liabilities  2008-09         42.30
39  Proportion of liabilities %  2008-09          9.40

Extract customer segment gap time series (Table 1.4)

In [30]:
# Extracts the customer segment time series from Table 1.4
t14_raw = tg_raw[tg_raw['SourceSheet'] == 'Table 1.4'].copy()
non_null_14 = [col for col in tg_raw.columns if t14_raw[col].notna().any()]

# Keeps only the columns that contain actual data for this table
t14 = t14_raw[non_null_14].copy()

segment_col = 'Table 1.4: Tax gap time series by customer group, percentage of total theoretical liabilities and £ billion'

# Filters out header rows and keeps only rows with valid segment information
data_14 = t14[t14[segment_col].notna() &
              ~t14[segment_col].isin(['Customer group', 'Tax gap as percentage of liability or £bn'])].copy()

# Renames the columns so the year columns are easy to work with
data_14.columns = ['SourceSheet', 'metric'] + year_labels + ['segment']

# Converts year values to numeric and removes percent symbols where present
for yr in year_labels:
    data_14[yr] = data_14[yr].astype(str).str.replace('%', '', regex=False)
    data_14[yr] = pd.to_numeric(data_14[yr], errors='coerce')

data_14 = data_14.drop(columns=['SourceSheet']).reset_index(drop=True)
print("Segments and metrics found:")
display(data_14[['segment', 'metric']])

Segments and metrics found:

,segment,metric
0,This worksheet contains 1 table.,NaN
1,This table contains detailed notes: [note 8][note 12],NaN
2,Estimates are rounded to the nearest £0.1 billion or the nearest 0.1%.,NaN
3,Small businesses,Tax gap as percentage of total theoretical liabilities
4,Small businesses,Tax gap in £bn
5,Criminals,Tax gap as percentage of total theoretical liabilities
6,Criminals,Tax gap in £bn
7,Mid-sized businesses,Tax gap as percentage of total theoretical liabilities
8,Mid-sized businesses,Tax gap in £bn
9,Large businesses,Tax gap as percentage of total theoretical liabilities
10,Large businesses,Tax gap in £bn
11,Individuals,Tax gap as percentage of total theoretical liabilities
12,Individuals,Tax gap in £bn
13,Wealthy,Tax gap as percentage of total theoretical liabilities
14,Wealthy,Tax gap in £bn
15,Total,Tax gap as percentage of total theoretical liabilities
16,Total,Tax gap in £bn

Pivoting to long format

In [32]:
# Reshaping the customer segment gap table so each row is one segment-year observation
segment_gap_long = data_14.melt(
    id_vars=['segment', 'metric'],
    var_name='year',
    value_name='value'
 )

# Separates percentage metrics from billion-pound metrics
seg_pct = segment_gap_long[
    segment_gap_long['metric'].str.contains('percentage', case=False)
].rename(columns={'value': 'gap_pct_of_liabilities'}).drop(columns='metric')

seg_bn = segment_gap_long[
    segment_gap_long['metric'].str.contains('£bn', case=False)
].rename(columns={'value': 'gap_gbp_bn'}).drop(columns='metric')

# Merges the two metric types into one table by segment and year
segment_gap_ts = seg_pct.merge(seg_bn, on=['segment', 'year'], how='outer')

print("Shape:", segment_gap_ts.shape)
display(segment_gap_ts.head(15))

Shape: (133, 4)

      segment     year  gap_pct_of_liabilities  gap_gbp_bn
0   Criminals  2005-06                    1.60        7.10
1   Criminals  2006-07                    1.30        6.10
2   Criminals  2007-08                    1.00        5.10
3   Criminals  2008-09                    1.30        6.00
4   Criminals  2009-10                    1.10        4.90
5   Criminals  2010-11                    1.00        4.60
6   Criminals  2011-12                    1.00        4.80
7   Criminals  2012-13                    1.00        5.00
8   Criminals  2013-14                    1.20        6.30
9   Criminals  2014-15                    0.90        4.80
10  Criminals  2015-16                    0.90        5.00
11  Criminals  2016-17                    0.80        4.90
12  Criminals  2017-18                    0.70        4.40
13  Criminals  2018-19                    0.70        4.90
14  Criminals  2019-20                    0.70        4.70

Assembling three focused analytical tables

Table A — Sector Risk Snapshot (cross-sectional, 2023-24)

This answers: Which sectors generate the most CT per company, and where does HMRC concentrate its activity?

In [ ]:
# Builds Table A: a sector snapshot for the most recent year
# Starts from the cleaned sector-level data extracted from Table 6
table_a = t6_sectors[[
    'sector_code', 'sector_name',
    'companies_filing_ct_return', 'companies_with_tax_payable',
    'total_profits_gbp_m', 'ct_payable_gbp_m',
    'trading_losses_gbp_m',
    'ct_per_company_gbp_k', 'effective_ct_rate_pct', 'loss_ratio_pct'
 ]].copy()

# Adds the latest sector liability and company count metrics from the time series tables
t8_latest = t8_section[['sector_code', 'liability_2023_24', 'liability_change_pct']]
table_a = table_a.merge(t8_latest, on='sector_code', how='left')
t9_latest = t9_section[['sector_code', 'companies_2023_24', 'company_count_change_pct']]
table_a = table_a.merge(t9_latest, on='sector_code', how='left')

# Excludes the special 'U' sector because it is not a normal economic sector
table_a = table_a[table_a['sector_code'] != 'U']

# Calculates each sector's share of total corporate tax payable
total_ct = table_a['ct_payable_gbp_m'].sum()
table_a['ct_share_pct'] = (table_a['ct_payable_gbp_m'] / total_ct * 100).round(2)

# Ranks sectors by CT payable, where 1 means highest CT payable
table_a['ct_rank'] = table_a['ct_payable_gbp_m'].rank(ascending=False).astype(int)

# Sorts sectors so the largest CT contributors are at the top
table_a = table_a.sort_values('ct_payable_gbp_m', ascending=False).reset_index(drop=True)

print("Table A shape:", table_a.shape)
display(table_a)

Table A shape: (0, 16)

Empty DataFrame
Columns: [sector_code, sector_name, companies_filing_ct_return, companies_with_tax_payable, total_profits_gbp_m, ct_payable_gbp_m, trading_losses_gbp_m, ct_per_company_gbp_k, effective_ct_rate_pct, loss_ratio_pct, liability_2023_24, liability_change_pct, companies_2023_24, company_count_change_pct, ct_share_pct, ct_rank]
Index: []

Spot checking key figures

In [34]:
# Shows a few quick checks on the sector snapshot data
print("Total CT payable across sectors: £{:,.0f}m".format(table_a['ct_payable_gbp_m'].sum()))
print("\nTop 5 sectors by CT payable:")
display(table_a[['sector_name', 'ct_payable_gbp_m', 'ct_share_pct', 'ct_per_company_gbp_k']].head(5))
print("\nTop 5 sectors by loss ratio (risk signal):")
display(table_a[['sector_name', 'loss_ratio_pct', 'ct_payable_gbp_m']].nlargest(5, 'loss_ratio_pct'))

Total CT payable across sectors: £0m

Top 5 sectors by CT payable:

Empty DataFrame
Columns: [sector_name, ct_payable_gbp_m, ct_share_pct, ct_per_company_gbp_k]
Index: []

Top 5 sectors by loss ratio (risk signal):

Empty DataFrame
Columns: [sector_name, loss_ratio_pct, ct_payable_gbp_m]
Index: []

Table B — Customer Segment Dashboard Table (cross-sectional, 2024-25)

This answers: Which customer segments have the highest tax gap and yield efficiency?

Building Table B from cleaned customer data

In [35]:
# Builds Table B: customer segment metrics for 2024-25
# Selects only the columns needed for the summary table
table_b = df_cust[[
    'segment', 'population',
    'paye_nics_receipts_gbp_bn', 'other_receipts_gbp_bn',
    'compliance_yield_gbp_bn', 'compliance_spend_gbp_m',
    'tax_gap_gbp_bn',
    'yield_pct_of_gap', 'spend_per_pound_yield', 'tax_gap_per_entity_gbp'
 ]].copy()

# Adding a total receipts column from PAYE/NICs and other receipts
table_b['total_receipts_gbp_bn'] = (
    table_b['paye_nics_receipts_gbp_bn'] + table_b['other_receipts_gbp_bn']
)
# Calculates the tax gap as a percentage of total receipts
table_b['gap_pct_of_receipts'] = (
    table_b['tax_gap_gbp_bn'] / table_b['total_receipts_gbp_bn'] * 100
).round(2)

# Defining the display order for customer segments
segment_order = {
    'Individual customers': 1,
    'Wealthy individuals': 2,
    'Small businesses': 3,
    'Mid-sized businesses (charities and public bodies)': 4,
    'Large businesses': 5
}
table_b['segment_order'] = table_b['segment'].map(segment_order)
table_b = table_b.sort_values('segment_order').reset_index(drop=True)

print("Table B:")
display(table_b)

Table B:

,segment,population,paye_nics_receipts_gbp_bn,other_receipts_gbp_bn,compliance_yield_gbp_bn,compliance_spend_gbp_m,tax_gap_gbp_bn,yield_pct_of_gap,spend_per_pound_yield,tax_gap_per_entity_gbp,total_receipts_gbp_bn,gap_pct_of_receipts,segment_order
0,Individual customers,37000000,355,20,3.50,540,2.20,159.10,0.15,59.00,375,0.59,1
1,Wealthy individuals,950000,70,55,3.70,290,2.10,176.20,0.08,"2,211.00",125,1.68,2
2,Small businesses,5100000,45,100,7.80,750,28.00,27.90,0.10,"5,490.00",145,19.31,3
3,Mid-sized businesses (charities and public bodies),380000,230,70,7.40,350,4.40,168.20,0.05,"11,579.00",300,1.47,4
4,Large businesses,2000,145,190,19.70,340,5.80,339.70,0.02,"2,900,000.00",335,1.73,5

Table C — Sector Trend Table (time series, 2018-19 to 2023-24)

This answers: How has sector-level CT liability and company population shifted over 6 years?

Building the long-format trend table

In [ ]:
# Builds Table C: a sector-level trend table over time
# Converts the section liability data from wide to long format
liability_long = t8_section.melt(
    id_vars='sector_code',
    value_vars=year_cols,
    var_name='year_col',
    value_name='ct_liability_gbp_m'
 )
liability_long['year'] = liability_long['year_col'].str.replace('liability_', '').str.replace('_', '-')
liability_long = liability_long.drop(columns='year_col')

# Converts the company count data from wide to long format
companies_long = t9_section.melt(
    id_vars='sector_code',
    value_vars=company_year_cols,
    var_name='year_col',
    value_name='companies_liable'
 )
companies_long['year'] = companies_long['year_col'].str.replace('companies_', '').str.replace('_', '-')
companies_long = companies_long.drop(columns='year_col')

# Merging the liability and company count tables by sector and year
table_c = liability_long.merge(companies_long, on=['sector_code', 'year'], how='left')

# Adding sector names for readability
sector_names = table_a[['sector_code', 'sector_name']].drop_duplicates()
table_c = table_c.merge(sector_names, on='sector_code', how='left')

# Calculating liability per company (in thousands of pounds)
table_c['liability_per_company_gbp_k'] = (
    (table_c['ct_liability_gbp_m'] * 1000) / table_c['companies_liable']
).round(1)

# Excluding the special 'U' category and sorting the rows
table_c = table_c[table_c['sector_code'] != 'U']
table_c = table_c.sort_values(['sector_code', 'year']).reset_index(drop=True)

print("Table C shape:", table_c.shape)
display(table_c.head(20))

Table C shape: (120, 6)

,sector_code,ct_liability_gbp_m,year,companies_liable,sector_name,liability_per_company_gbp_k
0,A,375.00,2018-19,"13,405.00",NaN,28.00
1,A,355.00,2019-20,"13,530.00",NaN,26.20
2,A,380.00,2020-21,"13,860.00",NaN,27.40
3,A,411.00,2021-22,"14,310.00",NaN,28.70
4,A,512.00,2022-23,"14,665.00",NaN,34.90
5,A,558.00,2023-24,"14,930.00",NaN,37.40
6,B,"2,173.00",2018-19,"3,725.00",NaN,583.40
7,B,"1,565.00",2019-20,"3,810.00",NaN,410.80
8,B,965.00,2020-21,"3,285.00",NaN,293.80
9,B,"2,400.00",2021-22,"2,835.00",NaN,846.60
10,B,"6,456.00",2022-23,"1,005.00",NaN,"6,423.90"
11,B,"3,078.00",2023-24,"2,605.00",NaN,"1,181.60"
12,C,"4,838.00",2018-19,"73,475.00",NaN,65.80
13,C,"3,940.00",2019-20,"63,855.00",NaN,61.70
14,C,"4,434.00",2020-21,"73,335.00",NaN,60.50
15,C,"5,245.00",2021-22,"74,000.00",NaN,70.90
16,C,"5,725.00",2022-23,"73,590.00",NaN,77.80
17,C,"6,857.00",2023-24,"75,105.00",NaN,91.30
18,D,975.00,2018-19,"3,565.00",NaN,273.50
19,D,"1,082.00",2019-20,"3,790.00",NaN,285.50

Building the Master Dashboard Dataframe

Joining everything into one wide, dashboard-ready table at the sector × year level, with the 2024-25 customer segment KPIs as a separate reference table

In [38]:
# Builds the master sector dashboard table from the long-form trend table
# Uses table_c which already contains sector-by-year liability and company counts
master_sector = table_c.copy()

# Adds the latest 2023-24 snapshot ratios from table_a
snapshot_cols = [
    'sector_code', 'effective_ct_rate_pct', 'loss_ratio_pct',
    'ct_per_company_gbp_k', 'ct_share_pct', 'ct_rank'
 ]
snapshot = table_a[snapshot_cols].copy()
snapshot['year'] = '2023-24'  # attach the latest year label
master_sector = master_sector.merge(snapshot, on=['sector_code', 'year'], how='left')

# Reordering columns to make the output easier to read
col_order = [
    'year', 'sector_code', 'sector_name',
    'ct_liability_gbp_m', 'companies_liable', 'liability_per_company_gbp_k',
    'effective_ct_rate_pct', 'loss_ratio_pct',
    'ct_share_pct', 'ct_rank'
 ]
master_sector = master_sector[col_order]

print("Master sector dataframe shape:", master_sector.shape)
display(master_sector.head(20))

Master sector dataframe shape: (120, 10)

,year,sector_code,sector_name,ct_liability_gbp_m,companies_liable,liability_per_company_gbp_k,effective_ct_rate_pct,loss_ratio_pct,ct_share_pct,ct_rank
0,2018-19,A,NaN,375.00,"13,405.00",28.00,NaN,NaN,NaN,NaN
1,2019-20,A,NaN,355.00,"13,530.00",26.20,NaN,NaN,NaN,NaN
2,2020-21,A,NaN,380.00,"13,860.00",27.40,NaN,NaN,NaN,NaN
3,2021-22,A,NaN,411.00,"14,310.00",28.70,NaN,NaN,NaN,NaN
4,2022-23,A,NaN,512.00,"14,665.00",34.90,NaN,NaN,NaN,NaN
5,2023-24,A,NaN,558.00,"14,930.00",37.40,NaN,NaN,NaN,NaN
6,2018-19,B,NaN,"2,173.00","3,725.00",583.40,NaN,NaN,NaN,NaN
7,2019-20,B,NaN,"1,565.00","3,810.00",410.80,NaN,NaN,NaN,NaN
8,2020-21,B,NaN,965.00,"3,285.00",293.80,NaN,NaN,NaN,NaN
9,2021-22,B,NaN,"2,400.00","2,835.00",846.60,NaN,NaN,NaN,NaN
10,2022-23,B,NaN,"6,456.00","1,005.00","6,423.90",NaN,NaN,NaN,NaN
11,2023-24,B,NaN,"3,078.00","2,605.00","1,181.60",NaN,NaN,NaN,NaN
12,2018-19,C,NaN,"4,838.00","73,475.00",65.80,NaN,NaN,NaN,NaN
13,2019-20,C,NaN,"3,940.00","63,855.00",61.70,NaN,NaN,NaN,NaN
14,2020-21,C,NaN,"4,434.00","73,335.00",60.50,NaN,NaN,NaN,NaN
15,2021-22,C,NaN,"5,245.00","74,000.00",70.90,NaN,NaN,NaN,NaN
16,2022-23,C,NaN,"5,725.00","73,590.00",77.80,NaN,NaN,NaN,NaN
17,2023-24,C,NaN,"6,857.00","75,105.00",91.30,NaN,NaN,NaN,NaN
18,2018-19,D,NaN,975.00,"3,565.00",273.50,NaN,NaN,NaN,NaN
19,2019-20,D,NaN,"1,082.00","3,790.00",285.50,NaN,NaN,NaN,NaN

Master customer segment dataframe (separate - different grain)

In [39]:
# Builds the master customer segment table for snapshot analysis
master_segment = table_b.drop(columns='segment_order').copy()  # segment_order is only for sorting

# Adds recent customer segment gap history for the latest five years
recent_years = ['2019-20', '2020-21', '2021-22', '2022-23', '2023-24']
seg_hist = segment_gap_ts[segment_gap_ts['year'].isin(recent_years)].copy()

# Maps the shorter segment names from Table 1.4 to the full names used in master_segment
seg_name_map = {
    'Small businesses':   'Small businesses',
    'Mid-sized businesses': 'Mid-sized businesses (charities and public bodies)',
    'Large businesses':   'Large businesses',
    'Individuals':        'Individual customers',
    'Wealthy':            'Wealthy individuals',
    'Total':              'Total'
}
seg_hist['segment'] = seg_hist['segment'].map(seg_name_map)
seg_hist = seg_hist[seg_hist['segment'].notna() & (seg_hist['segment'] != 'Total')]

print("Segment gap history (recent 5 years):")
display(seg_hist)
print("\nMaster segment snapshot:")
display(master_segment)

Segment gap history (recent 5 years):

,segment,year,gap_pct_of_liabilities,gap_gbp_bn
33,Individual customers,2019-20,0.30,2.10
34,Individual customers,2020-21,0.30,1.70
35,Individual customers,2021-22,0.30,2.50
36,Individual customers,2022-23,0.30,2.20
37,Individual customers,2023-24,0.20,2.20
52,Large businesses,2019-20,0.90,5.70
53,Large businesses,2020-21,0.60,3.90
54,Large businesses,2021-22,0.60,4.50
55,Large businesses,2022-23,0.80,6.90
56,Large businesses,2023-24,0.70,5.80
71,Mid-sized businesses (charities and public bodies),2019-20,0.90,5.80
72,Mid-sized businesses (charities and public bodies),2020-21,0.50,3.40
73,Mid-sized businesses (charities and public bodies),2021-22,0.50,3.90
74,Mid-sized businesses (charities and public bodies),2022-23,0.70,5.70
75,Mid-sized businesses (charities and public bodies),2023-24,0.50,4.40
90,Small businesses,2019-20,2.80,18.60
91,Small businesses,2020-21,3.10,19.60
92,Small businesses,2021-22,3.40,25.30
93,Small businesses,2022-23,3.10,25.90
94,Small businesses,2023-24,3.20,28.00
128,Wealthy individuals,2019-20,0.20,1.60
129,Wealthy individuals,2020-21,0.20,1.40
130,Wealthy individuals,2021-22,0.30,1.90
131,Wealthy individuals,2022-23,0.20,1.90
132,Wealthy individuals,2023-24,0.20,2.10

Master segment snapshot:

,segment,population,paye_nics_receipts_gbp_bn,other_receipts_gbp_bn,compliance_yield_gbp_bn,compliance_spend_gbp_m,tax_gap_gbp_bn,yield_pct_of_gap,spend_per_pound_yield,tax_gap_per_entity_gbp,total_receipts_gbp_bn,gap_pct_of_receipts
0,Individual customers,37000000,355,20,3.50,540,2.20,159.10,0.15,59.00,375,0.59
1,Wealthy individuals,950000,70,55,3.70,290,2.10,176.20,0.08,"2,211.00",125,1.68
2,Small businesses,5100000,45,100,7.80,750,28.00,27.90,0.10,"5,490.00",145,19.31
3,Mid-sized businesses (charities and public bodies),380000,230,70,7.40,350,4.40,168.20,0.05,"11,579.00",300,1.47
4,Large businesses,2000,145,190,19.70,340,5.80,339.70,0.02,"2,900,000.00",335,1.73

Validating & Exporting

Final shape checks

In [40]:
# Validating the final prepared tables by printing shape and completeness information
print("=== FINAL DATAFRAME SUMMARY ===\n")

print("master_sector:")
print(f"  Shape:   {master_sector.shape}")
print(f"  Years:   {sorted(master_sector['year'].unique())}")
print(f"  Sectors: {master_sector['sector_code'].nunique()}")
print(f"  Nulls:\n{master_sector.isnull().sum()}\n")

print("master_segment (snapshot):")
print(f"  Shape:   {master_segment.shape}")
print(f"  Segments:{master_segment['segment'].tolist()}\n")

print("seg_hist (time series, 5 years):")
print(f"  Shape:   {seg_hist.shape}")
print(f"  Years:   {sorted(seg_hist['year'].unique())}\n")

print("ct_gap_long (CT gap time series):")
print(f"  Shape:   {ct_gap_long.shape}")
print(f"  Years:   {ct_gap_long['year'].nunique()} years\n")

=== FINAL DATAFRAME SUMMARY ===

master_sector:
  Shape:   (120, 10)
  Years:   ['2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']
  Sectors: 20
  Nulls:
year                             0
sector_code                      0
sector_name                    120
ct_liability_gbp_m               0
companies_liable                 0
liability_per_company_gbp_k      0
effective_ct_rate_pct          120
loss_ratio_pct                 120
ct_share_pct                   120
ct_rank                        120
dtype: int64

master_segment (snapshot):
  Shape:   (5, 12)
  Segments:['Individual customers', 'Wealthy individuals', 'Small businesses', 'Mid-sized businesses (charities and public bodies)', 'Large businesses']

seg_hist (time series, 5 years):
  Shape:   (25, 4)
  Years:   ['2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

ct_gap_long (CT gap time series):
  Shape:   (95, 3)
  Years:   19 years

Answering the project questions explicitly

In [41]:
# Answers the project questions using the cleaned tables
print("Q1: Which sectors generate the most CT liability per company?")
display(master_sector[master_sector['year'] == '2023-24']
        .nlargest(5, 'liability_per_company_gbp_k')
        [['sector_name', 'liability_per_company_gbp_k', 'ct_liability_gbp_m']])

print("\nQ2: How does compliance yield compare to the tax gap by segment?")
display(master_segment[['segment', 'tax_gap_gbp_bn', 'compliance_yield_gbp_bn',
                         'yield_pct_of_gap', 'tax_gap_per_entity_gbp']])

print("\nQ3: Which sectors have grown fastest in CT liability 2018-2023?")
display(t8_section[['sector_code', 'liability_2018_19', 'liability_2023_24',
                     'liability_change_pct']]
        .merge(sector_names, on='sector_code')
        .nlargest(5, 'liability_change_pct')
        [['sector_name', 'liability_2018_19', 'liability_2023_24', 'liability_change_pct']])

print("\nQ4: Which segments have the highest tax gap as % of receipts?")
display(master_segment[['segment', 'gap_pct_of_receipts', 'tax_gap_gbp_bn',
                         'total_receipts_gbp_bn']].sort_values('gap_pct_of_receipts', ascending=False))

Q1: Which sectors generate the most CT liability per company?

   sector_name  liability_per_company_gbp_k  ct_liability_gbp_m
11         NaN                     1,181.60            3,078.00
23         NaN                     1,124.30            5,183.00
65         NaN                       436.80           19,581.00
89         NaN                        95.10              302.00
17         NaN                        91.30            6,857.00

Q2: How does compliance yield compare to the tax gap by segment?

,segment,tax_gap_gbp_bn,compliance_yield_gbp_bn,yield_pct_of_gap,tax_gap_per_entity_gbp
0,Individual customers,2.20,3.50,159.10,59.00
1,Wealthy individuals,2.10,3.70,176.20,"2,211.00"
2,Small businesses,28.00,7.80,27.90,"5,490.00"
3,Mid-sized businesses (charities and public bodies),4.40,7.40,168.20,"11,579.00"
4,Large businesses,5.80,19.70,339.70,"2,900,000.00"

Q3: Which sectors have grown fastest in CT liability 2018-2023?

Empty DataFrame
Columns: [sector_name, liability_2018_19, liability_2023_24, liability_change_pct]
Index: []

Q4: Which segments have the highest tax gap as % of receipts?

,segment,gap_pct_of_receipts,tax_gap_gbp_bn,total_receipts_gbp_bn
2,Small businesses,19.31,28.00,145
4,Large businesses,1.73,5.80,335
1,Wealthy individuals,1.68,2.10,125
3,Mid-sized businesses (charities and public bodies),1.47,4.40,300
0,Individual customers,0.59,2.20,375

Exporting all dashboard-ready tables

In [42]:
# Exports the final tables to CSV files so they can be used in the dashboard 
master_sector.to_csv('dashboard_sector_timeseries.csv', index=False)
master_segment.to_csv('dashboard_segment_snapshot.csv', index=False)
seg_hist.to_csv('dashboard_segment_gap_history.csv', index=False)
ct_gap_long.to_csv('dashboard_ct_gap_timeseries.csv', index=False)

# Confirming the export files and describing what they contain
print("Exported:")
print("  dashboard_sector_timeseries.csv   — sector × year with CT, companies, ratios")
print("  dashboard_segment_snapshot.csv    — 2024-25 KPIs by customer segment")
print("  dashboard_segment_gap_history.csv — tax gap trend by segment, last 5 years")
print("  dashboard_ct_gap_timeseries.csv   — overall CT gap trend since 2005-06")

Exported:
  dashboard_sector_timeseries.csv   — sector × year with CT, companies, ratios
  dashboard_segment_snapshot.csv    — 2024-25 KPIs by customer segment
  dashboard_segment_gap_history.csv — tax gap trend by segment, last 5 years
  dashboard_ct_gap_timeseries.csv   — overall CT gap trend since 2005-06